---
locale: es
tags: []
layout: input_bottom
editor: 0
type: playground
extra_visible: true
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
name: Acciones y consultas
