---
locale: es
tags: []
layout: input_bottom
editor: 0
type: playground
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
name: "¿Bloques? ¿Qué es eso?"
